Add a switch command to pgenv
theory/pgenv pull request #53
Opened 2022-05-04 12:52 UTC by thanodnl

The switch command acts mostly like use, however, it does not manage any database for you, it simply changes the version linked and thus in the path of the user.

When developing the citus extension for postgres we often need to manage many different postgres databases running on the same machine (different ports) at once. We have our own tooling to create these databases from the postgres version installed on the path.

By omitting the starting, stopping and initializing of the database we can still use `pgenv` to manage different versions of postgres on the same machine.

Last years we used a fork of `pgenv` with some more functionality hacked in. Over time most of that functionality have been better implemented by the `pgenv` community. The last missing piece for now is a lightweight way of switching which postgres version is on the path without managing a database.

2022-05-04 13:31 UTC, fluca1978 commented
This is interesting, but seems to me it should do the very same thing as `use` without starting the PostgreSQL version (but stopping the one running if any).
Should we implemented with a subcase of `use` then?

2022-05-04 15:13 UTC, thanodnl commented
I think stopping a database if running makes a lot of sense.

with a subcase of `use`, do you think about adding a flag (I don't see many flags used within pgenv) or reuse most of the logics from `use`, simply skipping the starting of the database.

I will push a change with the latter implemented.

2022-05-05 06:56 UTC, fluca1978 commented
Uhm, the error is coming from `pgenv_stop_or_restart_instance`. However such message seems only informative, to warn the user. 
What if we change such message from <https://github.com/theory/pgenv/blob/master/bin/pgenv#L927>:

```
echo "PostgreSQL $v not running"
```

to something like:

```
echo "WARN: PostgreSQL $v not running" >&2
```

so that it is clear that the message is not an error for `pgenv`. After all, you do a `switch` and the program reminds you the system is not running. What do you think?

Then the `switch` + `use` branch should look fine.

2022-05-05 09:49 UTC, thanodnl commented
To start with, I am ok with the output as is. Although a bit strange in our workflow, there is nothing problematic with the message.

I would refrain from routing the message to stderr, as it is not really an error. Better to keep it on stdout for now.

That said, it is a bit strange in UX that it would _only_ say something about the old version when switching. Not to say I would want to add more output telling what the new version is. In general I would expect tools to be quiet when things simply work. And only provide information if it needed to course correct to make it work.

eg. instead of logging that postgres wasn't running on the old version I would _only_ tell the user we have detected the old version was running and we are shutting it down. This provides good insights in what the tool was doing, not wat it was not doing. However this would change the normal workflow for people being used to the `use` command.

Lets merge this as is, and see what others think about its chattyness.

2022-05-05 10:56 UTC, fluca1978 commented
Well, I'm fine with removing messages that told "something did not happen" in favor of what "did happen".

I think this can be merged, and imrpove the messaging later. The only doubt I've is if we need to work on messaging before the new release is done. @theory are you okay with this?

2022-05-07 16:43 UTC, theory commented
Maybe emit the message only when in a verbose or debugging mode?

2022-05-07 16:44 UTC, theory approved these changes

2022-05-10 08:26 UTC, fluca1978 commented
@thanodnl would you mind fixing the documentation as suggested and resolving the pending comments, then we can squash and merge.

2022-05-10 14:01 UTC, fluca1978 commented
Uhm, I see a couple of pending comments regarding documentation. It could be that the approval has removed these comments on your side?
By the way, if you don't see any pending comment please advice, I will merge and fix a few things in the documentation.

2022-05-10 14:39 UTC, thanodnl commented
If you see the word pending on the comment like below:

<img width="667" alt="Screenshot 2022-05-10 at 16 37 42" src="https://user-images.githubusercontent.com/273145/167654872-f9ddeeb6-4c8f-4dd9-bd39-52f48308fc9f.png">

No one, but you, can see the comments. To make them visible you should submit your review from the `files` tab via the big green button saying `Finish Review`

2022-05-10 16:58 UTC, fluca1978 requested changes

2022-05-11 06:35 UTC, fluca1978 commented
Sorry @thanodnl , my fault! Now you should be able to proceed to changes.
Also please rebase, since I've removed the `stop` message from the output.

2022-05-11 11:46 UTC, thanodnl commented on README.md
> +    switch     Set the current PostgreSQL version
makes sense to me, I have re-arranged `use`/`start`/`stop` to be together for that reason, and moved, `switch`/`clear` below that section.

2022-05-11 12:21 UTC, fluca1978 approved these changes

2022-05-11 12:23 UTC, merged

2022-05-11 12:24 UTC, fluca1978 commented
Thnaks @thanodnl